
// Shim for Node.js execution
// @ts-ignore
if (typeof import.meta === 'undefined') (global as any).import = { meta: { env: { VITE_GOOGLE_MAPS_API_KEY: 'mock-key' } } };
// @ts-ignore
if (!import.meta.env) (import.meta as any).env = { VITE_GOOGLE_MAPS_API_KEY: 'mock-key' };

import { OptimizationService } from './src/services/optimization.service';
import { PatientService } from './src/services/patient.service';
import { sites, siteInventories } from './src/data/location/mockData';
import { Patient } from './src/types/patient';

async function verifyProposals() {
    console.log("--- VERIFYING PATIENT-CENTRIC & EOQ LOGIC ---");

    // 1. Create Profiled Patients
    const oncologyPatient: Patient = {
        id: 'pat-onco', mrn: 'M-1', name: 'Onco Bob', dateOfBirth: '1960-01-01', gender: 'male',
        diagnosis: 'Stage IV Lung Cancer', type: 'oncology',
        attendingPhysician: 'Dr. House', treatmentSchedule: [],
        assignedSiteId: sites[0].id, assignedDepartmentId: sites[0].departments![0].id,
        biometrics: { weight: 90, height: 185, bsa: 2.15 } // High BSA (2.15 > 1.73 avg)
    };
    // 2.15 * 100 = 215mg -> 3 vials (100mg each) 
    oncologyPatient.treatmentSchedule = PatientService.generateSchedule('Cancer');
    // Force drug to be Keytruda for consistent testing
    oncologyPatient.treatmentSchedule.forEach(t => {
        t.drugName = 'Keytruda 100mg Vial';
        t.ndc = '0006-3026-02';
    });

    const pedsPatient: Patient = {
        id: 'pat-peds', mrn: 'M-2', name: 'Tiny Tim', dateOfBirth: '2015-01-01', gender: 'male',
        diagnosis: 'Juvenile Diabetes', type: 'pediatric',
        attendingPhysician: 'Dr. House', treatmentSchedule: [],
        assignedSiteId: sites[0].id, assignedDepartmentId: sites[0].departments![0].id,
        biometrics: { weight: 15, height: 90, bsa: 0.6 } // 15kg
    };
    // 15kg / 30kg = 0.5 -> 1 vial

    const patients = [oncologyPatient, pedsPatient];

    // 2. Run Optimization
    // Force a forecasted need by ensuring dates align (ForecastingService checks 90 days from now)
    // The generator already does this.

    console.log("Running Optimization...");
    const proposals = await OptimizationService.generateProposals(sites, siteInventories, patients, []);

    // 3. Inspect Results
    console.log("\n--- RESULTS ---");
    proposals.forEach(p => {
        console.log(`[${p.type.toUpperCase()}] ${p.drugName}: Qty ${p.quantity} | Cost $${p.costAnalysis.totalCost.toFixed(2)}`);
        if (p.drugName.includes('Keytruda')) {
            console.log(`-> Analysis: Likely generated by Oncology Bob. Quantity ${p.quantity} should be influenced by BSA.`);
        }
    });

    // 4. Validate EOQ (Implicitly checked via Purchase Quantity)
    // If we see quantities like 14 (sqrt(2*Demand*50/Holding)) for small deficits, EOQ is working.

    // Check Scaling again briefly
    console.log("\n--- QUICK SCALING CHECK ---");
    const bulkPatients = PatientService.generateMockPatients(50);
    const bulkProposals = await OptimizationService.generateProposals(sites, siteInventories, bulkPatients, []);
    const totalQty = bulkProposals.reduce((sum, p) => sum + p.quantity, 0);
    console.log(`50 Random Patients -> ${bulkProposals.length} Proposals, ${totalQty} Total Units.`);
}

verifyProposals();
