import { useState, useMemo } from 'react';
import { ClipboardList, Stethoscope, TrendingDown, Calendar, Syringe, Clock, User, FileText, ChevronRight } from 'lucide-react';
import { clinicalService } from '../services/clinicalService';
import type { PreferenceCard, UsageReport } from '../services/clinicalService';
import { CaseCartModal } from '../components/clinical/CaseCartModal';
import { PreferenceCardView } from '../components/clinical/PreferenceCardView';
import { CalendarGrid } from '../components/clinical/CalendarGrid';
import toast from 'react-hot-toast';
import { useApp } from '../context/AppContext';

export function ClinicalHub() {
    const { patients } = useApp();
    const [activeTab, setActiveTab] = useState<'cards' | 'vac' | 'schedule'>('schedule');
    const [selectedCase, setSelectedCase] = useState<{ patient: string; procedure: string; surgeon: string } | null>(null);
    const [currentDate, setCurrentDate] = useState(new Date());
    const [selectedDate, setSelectedDate] = useState<Date | null>(new Date());

    // -- DATA FETCHING --
    // Use global unified patients instead of regenerating
    // const patients = useMemo(() => PatientService.generateMockPatients(50), []);

    // Transform patient treatments into calendar events
    const events = useMemo(() => {
        const allEvents: any[] = [];

        patients.forEach(patient => {
            patient.treatmentSchedule.forEach(treatment => {
                allEvents.push({
                    id: treatment.id,
                    date: new Date(treatment.date),
                    type: treatment.drugName.includes('Ancef') ? 'surgery' : 'treatment', // Simple heuristic for demo
                    title: treatment.drugName,
                    patientName: patient.name,
                    details: treatment,
                    verified: Math.random() > 0.3
                });
            });
        });

        // Add some explicit surgery events if not generated by the random heuristic
        if (!allEvents.some(e => e.type === 'surgery')) {
            const today = new Date();
            allEvents.push({
                id: 'surg-1',
                date: today,
                type: 'surgery',
                title: 'Total Knee Arthroplasty',
                patientName: 'James Wilson',
                surgeon: 'Dr. Chen',
                verified: true
            });
        }

        return allEvents;
    }, [patients]);

    // Get events for the selected date
    const selectedDateEvents = useMemo(() => {
        if (!selectedDate) return [];
        return events.filter(e => e.date.toDateString() === selectedDate.toDateString());
    }, [selectedDate, events]);


    // Mock Data for Demo
    const [card, setCard] = useState<PreferenceCard>({
        id: '1',
        procedureName: 'Total Knee Arthroplasty',
        surgeonName: 'Dr. Sarah Chen',
        items: [
            { itemId: '1', name: 'Surgical Gloves Size 7', quantity: 4, openStatus: 'open' },
            { itemId: '2', name: 'Bone Cement (Simplex P)', quantity: 2, openStatus: 'open' },
            { itemId: '3', name: 'Suction Canister 2000ml', quantity: 3, openStatus: 'open' },
            { itemId: '4', name: 'Antibiotic Irrigation', quantity: 1, openStatus: 'hold' },
            { itemId: '5', name: '#15 Blade', quantity: 2, openStatus: 'open' },
        ]
    });

    const mockHistory: UsageReport[] = [
        { procedureId: 'p1', itemsUsed: [{ itemId: '1', quantity: 2 }, { itemId: '2', quantity: 1 }, { itemId: '3', quantity: 3 }] },
        { procedureId: 'p2', itemsUsed: [{ itemId: '1', quantity: 2 }, { itemId: '2', quantity: 1 }, { itemId: '3', quantity: 3 }] },
        { procedureId: 'p3', itemsUsed: [{ itemId: '1', quantity: 3 }, { itemId: '2', quantity: 1 }, { itemId: '3', quantity: 2 }] },
    ];

    const recommendations = clinicalService.analyzePreferenceCard(card, mockHistory);

    // Mock Schedule Data
    // const schedule = [
    //     { time: '07:30', patient: 'James Wilson', procedure: 'Total Knee Arthroplasty', surgeon: 'Dr. Chen', or: 'OR-1', status: 'In Prep', drugs: ['Ancef 2g', 'Tranexamic Acid 1g'] },
    //     { time: '09:00', patient: 'Maria Garcia', procedure: 'Laparoscopic Cholecystectomy', surgeon: 'Dr. Smith', or: 'OR-3', status: 'Scheduled', drugs: ['Rocephin 1g'] },
    //     { time: '10:15', patient: 'Robert Taylor', procedure: 'Hernia Repair', surgeon: 'Dr. Jones', or: 'OR-2', status: 'Scheduled', drugs: ['Ancef 1g'] },
    //     { time: '12:30', patient: 'Linda Brown', procedure: 'Hip Replacement', surgeon: 'Dr. Chen', or: 'OR-1', status: 'Scheduled', drugs: ['Vancomycin 1g', 'Tranexamic Acid 1g'] },
    // ];

    return (
        <div className="space-y-6 p-6">
            <div className="flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-center sm:justify-between">
                <div>
                    <h1 className="text-2xl font-bold text-slate-900">Clinical Operations</h1>
                    <p className="text-sm text-slate-500">Bridge the gap between supply chain and patient care.</p>
                </div>
                <div className="flex rounded-lg bg-slate-100 p-1">
                    <button
                        onClick={() => setActiveTab('schedule')}
                        className={`flex items-center gap-2 rounded-md px-3 py-1.5 text-sm font-medium transition-all ${activeTab === 'schedule' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-900'}`}
                    >
                        <Calendar className="h-4 w-4" />
                        Schedule
                    </button>
                    <button
                        onClick={() => setActiveTab('cards')}
                        className={`flex items-center gap-2 rounded-md px-3 py-1.5 text-sm font-medium transition-all ${activeTab === 'cards' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-900'}`}
                    >
                        <ClipboardList className="h-4 w-4" />
                        Preference Cards
                    </button>
                    <button
                        onClick={() => setActiveTab('vac')}
                        className={`flex items-center gap-2 rounded-md px-3 py-1.5 text-sm font-medium transition-all ${activeTab === 'vac' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-900'}`}
                    >
                        <Stethoscope className="h-4 w-4" />
                        Value Analysis
                    </button>
                </div>
            </div>

            {activeTab === 'schedule' && (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    {/* Calendar Grid */}
                    <div className="lg:col-span-2">
                        <CalendarGrid
                            currentDate={currentDate}
                            events={events}
                            onDateChange={setCurrentDate}
                            onSelectDate={setSelectedDate}
                            selectedDate={selectedDate}
                        />
                    </div>

                    {/* Daily Detail View */}
                    <div className="bg-white rounded-xl border border-slate-200 shadow-sm flex flex-col h-[600px]">
                        <div className="p-4 border-b border-slate-200 bg-slate-50 rounded-t-xl">
                            <h3 className="font-bold text-slate-900 flex items-center gap-2">
                                <Calendar className="h-4 w-4 text-slate-500" />
                                {selectedDate ? selectedDate.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }) : 'Select a date'}
                            </h3>
                            <p className="text-xs text-slate-500 mt-1">
                                {selectedDateEvents.length} scheduled events
                            </p>
                        </div>

                        <div className="flex-1 overflow-y-auto p-4 space-y-3">
                            {selectedDateEvents.length === 0 ? (
                                <div className="h-full flex flex-col items-center justify-center text-slate-400">
                                    <Calendar className="h-12 w-12 mb-3 opacity-20" />
                                    <p>No events scheduled</p>
                                </div>
                            ) : (
                                selectedDateEvents.map((event, i) => (
                                    <div key={i} className="group flex flex-col gap-3 p-4 rounded-lg border border-slate-100 hover:border-blue-200 hover:bg-blue-50/30 transition-all bg-white shadow-sm">
                                        <div className="flex justify-between items-start">
                                            <div className="flex items-center gap-2">
                                                <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wide ${event.type === 'surgery' ? 'bg-amber-100 text-amber-700' : 'bg-blue-100 text-blue-700'
                                                    }`}>
                                                    {event.type}
                                                </span>
                                                <span className="text-xs text-slate-500 font-mono">
                                                    {event.date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
                                                </span>
                                            </div>
                                            {event.type === 'surgery' && (
                                                <button
                                                    onClick={() => setSelectedCase({ patient: event.patientName, procedure: event.title, surgeon: event.surgeon || 'Dr. Chen' })}
                                                    className="text-xs font-semibold text-blue-600 hover:text-blue-800 flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity"
                                                >
                                                    View Cart <ChevronRight className="h-3 w-3" />
                                                </button>
                                            )}
                                        </div>

                                        <div>
                                            <h4 className="font-bold text-slate-900">{event.title}</h4>
                                            <div className="flex items-center gap-4 mt-1 text-sm text-slate-600">
                                                <span className="flex items-center gap-1">
                                                    <User className="h-3 w-3" /> {event.patientName}
                                                </span>
                                                {event.surgeon && (
                                                    <span className="flex items-center gap-1">
                                                        <Stethoscope className="h-3 w-3" /> {event.surgeon}
                                                    </span>
                                                )}
                                            </div>
                                        </div>

                                        {/* Supply Status */}
                                        <div className="mt-2 pt-2 border-t border-slate-50 flex items-center justify-between">
                                            <span className="text-xs text-slate-500 flex items-center gap-1">
                                                <Syringe className="h-3 w-3" /> Supply Check
                                            </span>
                                            <span className={`text-xs font-bold ${event.verified ? 'text-emerald-600' : 'text-amber-600'}`}>
                                                {event.verified ? 'READY' : 'PENDING'}
                                            </span>
                                        </div>
                                    </div>
                                ))
                            )}
                        </div>
                    </div>
                </div>
            )}

            {activeTab === 'cards' && (
                <div className="grid gap-6 lg:grid-cols-2">
                    {/* Interactive Card View */}
                    <PreferenceCardView
                        card={card}
                        history={mockHistory}
                        onSave={(updatedCard) => {
                            setCard(updatedCard);
                            toast.success('Preference card updated');
                        }}
                    />

                    {/* Stats Panel */}
                    <div className="space-y-6">
                        <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
                            <h3 className="mb-4 text-lg font-bold text-slate-900">Optimization Opportunities</h3>
                            <div className="space-y-4">
                                {recommendations.map((rec, i) => (
                                    <div key={i} className="flex items-start gap-3 rounded-lg border border-slate-100 bg-slate-50 p-4">
                                        <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-indigo-100 text-indigo-600">
                                            <TrendingDown className="h-4 w-4" />
                                        </div>
                                        <div className="flex-1">
                                            <div className="flex items-center justify-between">
                                                <p className="font-medium text-slate-900">{rec.itemName}</p>
                                                <span className="text-xs font-bold text-emerald-600">+${rec.potentialSavings} savings</span>
                                            </div>
                                            <p className="mt-1 text-sm text-slate-600">
                                                Average usage only <span className="font-bold">{rec.avgUsed}</span> vs opened <span className="font-bold">{rec.currentQty}</span>.
                                            </p>
                                            <button
                                                onClick={() => toast.success('Optimization applied to all future cases')}
                                                className="mt-2 text-xs font-bold text-indigo-600 hover:text-indigo-800"
                                            >
                                                Apply Recommendation
                                            </button>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <div className="rounded-xl bg-emerald-50 p-6 border border-emerald-100">
                                <p className="text-sm font-bold text-emerald-800 uppercase tracking-wide">Annual Savings</p>
                                <p className="mt-2 text-3xl font-bold text-emerald-900">$142k</p>
                                <p className="text-xs text-emerald-700 mt-1">Projected from 24 optimizations</p>
                            </div>
                            <div className="rounded-xl bg-blue-50 p-6 border border-blue-100">
                                <p className="text-sm font-bold text-blue-800 uppercase tracking-wide">Card Accuracy</p>
                                <p className="mt-2 text-3xl font-bold text-blue-900">92%</p>
                                <p className="text-xs text-blue-700 mt-1">Up 12% this quarter</p>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {activeTab === 'vac' && (
                <div className="flex flex-col items-center justify-center rounded-xl border border-slate-200 bg-white p-12 text-center min-h-[400px]">
                    <div className="mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-slate-50 ring-8 ring-slate-50">
                        <Stethoscope className="h-10 w-10 text-slate-400" />
                    </div>
                    <h3 className="text-xl font-bold text-slate-900">Value Analysis Portal</h3>
                    <p className="mt-2 text-slate-500 max-w-md">Submit new product requests for clinical and financial review. Track usage trials and outcomes.</p>
                    <button
                        onClick={() => toast('VAC Request Form coming in next sprint', { icon: '📝' })}
                        className="mt-8 rounded-xl bg-indigo-600 px-6 py-3 text-sm font-bold text-white hover:bg-indigo-700 shadow-lg shadow-indigo-200 transition-all hover:scale-105"
                    >
                        Start New Request
                    </button>
                </div>
            )}

            {/* Modals */}
            <CaseCartModal
                isOpen={!!selectedCase}
                onClose={() => setSelectedCase(null)}
                patientName={selectedCase?.patient || ''}
                procedureName={selectedCase?.procedure || ''}
                surgeonName={selectedCase?.surgeon || ''}
            />
        </div>
    );
}
